AuraAndTheChamberOfSecrets/Controllers/QuestionController.cs
using System;
using System.Threading.Tasks;
using AuraAndTheChamberOfSecrets.Models;
using AuraAndTheChamberOfSecrets.Services.Interface;
using AuraAndTheChamberOfSecrets.ViewModels.Question;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AuraAndTheChamberOfSecrets.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionService _questionService;
        private readonly IAccountService _accountService;

        public QuestionController(IQuestionService questionService, IAccountService accountService)
        {
            _questionService = questionService;
            _accountService = accountService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(SearchViewModel search)
        {
            if (!ModelState.IsValid)
            {
                return View(search);
            }

            search.SearchResults = await _questionService.SearchQuestionsAsync(search.SearchString);

            return View(search);
        }

        [HttpGet]
        public IActionResult Ask()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Ask(AskViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var user = _accountService.GetUserProfileByUsername(User.Identity.Name);

            var question = new Question
            {
                Title = vm.Title,
                QuestionText = vm.QuestionText,
                User = user
            };
            await _questionService.CreateQuestionAsync(question);

            return RedirectToAction(nameof(Detail), new {question.Id});
        }

        /// <summary>
        /// todo - restrict access to users who are part of the organization this question belongs to
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        [Route("[controller]/{id:Guid}/[action]")]
        public IActionResult Detail(Guid id)
        {
            var question = _questionService.GetQuestion(id);

            var vm = new DetailViewModel {Question = question};

            return View(vm);
        }

        [HttpPost]
        [Route("[controller]/{id:Guid}/[action]")]
        public async Task<IActionResult> Detail(DetailViewModel vm, Guid id)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var user = _accountService.GetUserProfileByUsername(User.Identity.Name);

            var answer = new Answer
            {
                AnswerText = vm.NewAnswer,
                User = user
            };
            await _questionService.AddAnswerAsync(answer, id);

            return RedirectToAction(nameof(Detail), new {id});
        }
    }
}

AuraAndTheChamberOfSecrets/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Aura and the Chamber of Secrets</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    
    @RenderSection("Styles", false)
</head>
<body>

    <div class="container mb-4">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top justify-content-between">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Chamber of Secrets</a>



            @if (User.Identity.IsAuthenticated)
            {
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Question" asp-action="Ask">Ask Question</a>
                        </li>
                    </ul>
                    <form asp-controller="Question" asp-action="Search" method="get" class="form form-inline mx-auto">
                        <div class="input-group">
                            <input type="text" name="SearchString" class="form-control" />
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </div>
                    </form>
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @User.Identity.Name
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownUser">
                                <form asp-controller="Account" asp-action="Logout" class="form">
                                    <button type="submit" class="dropdown-item" title="Logout">Logout</button>
                                </form>
                            </div>
                        </li>
                    </ul>
                </div>
            }
            else
            {
                <form asp-controller="Question" asp-action="Search" method="get" class="form form-inline mx-auto">
                    <div class="input-group">
                        <input type="text" name="SearchString" class="form-control" />
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-primary">Search</button>
                        </div>
                    </div>
                </form>
                <form asp-controller="Account" asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form form-inline">
                    <button type="submit" class="btn btn-primary" name="provider" value="Google" title="Log in using your Google account">Login with Google</button>
                </form>
            }
        </nav>
    </div>

    @RenderBody()

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>